name: ci-dictionary-workflow
on: [push]

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Baixa os arquivos que acabaram de subir
      - uses: actions/setup-node@v4 # Prepara o ambiente para o Node
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - run: npm run start
